/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CourseManage;

import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class TeacherSignUp extends javax.swing.JFrame {

    /**
     * Creates new form AddUserForm
     */
    user u = new user();
    public TeacherSignUp() {
        initComponents();
         lbl_U.setVisible(false);
        lbl_P.setVisible(false);
        lbl_P2.setVisible(false);
        lbl_Pmatch.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jPasswordField_password2 = new javax.swing.JPasswordField();
        button_addUser = new java.awt.Button();
        button_cancel = new java.awt.Button();
        lbl_U = new javax.swing.JLabel();
        lbl_P = new javax.swing.JLabel();
        jPasswordField_password1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        lbl_P2 = new javax.swing.JLabel();
        lbl_Pmatch = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_course = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_fname = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setForeground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Swis721 BdOul BT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Add Teacher ");

        jLabel2.setFont(new java.awt.Font("Humnst777 BT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Humnst777 BT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Password:");

        jTextField_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });

        jPasswordField_password2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField_password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_password2ActionPerformed(evt);
            }
        });

        button_addUser.setBackground(java.awt.Color.lightGray);
        button_addUser.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button_addUser.setForeground(new java.awt.Color(0, 0, 51));
        button_addUser.setLabel("Add");
        button_addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addUserActionPerformed(evt);
            }
        });
        button_addUser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                button_addUserPropertyChange(evt);
            }
        });

        button_cancel.setBackground(java.awt.Color.lightGray);
        button_cancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button_cancel.setForeground(new java.awt.Color(0, 0, 51));
        button_cancel.setLabel("Back");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });
        button_cancel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                button_cancelPropertyChange(evt);
            }
        });

        lbl_U.setBackground(new java.awt.Color(255, 0, 0));
        lbl_U.setForeground(new java.awt.Color(255, 255, 255));
        lbl_U.setText("username is required");

        lbl_P.setBackground(new java.awt.Color(255, 0, 0));
        lbl_P.setForeground(new java.awt.Color(255, 255, 255));
        lbl_P.setText("password is required");

        jPasswordField_password1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Humnst777 BT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Confirm password:");

        lbl_P2.setBackground(new java.awt.Color(255, 0, 0));
        lbl_P2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_P2.setText("re-write password ");

        lbl_Pmatch.setBackground(new java.awt.Color(255, 0, 0));
        lbl_Pmatch.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Pmatch.setText("Passwords dont match ");

        jLabel5.setFont(new java.awt.Font("Humnst777 BT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Course:");

        jTextField_course.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_courseActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Humnst777 BT", 1, 18)); // NOI18N
        jLabel6.setText("Full Name:");

        jTextField_fname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fnameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_fname, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jTextField_username))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_U))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button_addUser, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_course, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addComponent(jPasswordField_password2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPasswordField_password1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_Pmatch)
                                    .addGap(17, 17, 17))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_P)
                            .addComponent(lbl_P2))))
                .addGap(126, 126, 126))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_U)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_password1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_P)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_password2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_P2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Pmatch)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_course, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addComponent(button_addUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addUserActionPerformed
        lbl_U.setVisible(false);
        lbl_P.setVisible(false);
        lbl_P2.setVisible(false);
        lbl_Pmatch.setVisible(false);
        if(jTextField_username.getText().equals("") )
        {
            lbl_U.setVisible(true);
        }if(String.valueOf(jPasswordField_password1.getPassword()).equals("") )
        {
            lbl_P.setVisible(true);
        }
        if(String.valueOf(jPasswordField_password2.getPassword()).equals(""))
         {
                lbl_P2.setVisible(true);
                lbl_Pmatch.setVisible(false);
                
         }
         
        else
        {
            if( u.isUserExist(jTextField_username.getText()))
                 {JOptionPane.showMessageDialog(null, "The username already exists Try with a different username","Register Failed",2);}
            else if(String.valueOf(jPasswordField_password1.getPassword()).equals(String.valueOf(jPasswordField_password2.getPassword()))){
            Connection con = MyConnection.getConnection();
            PreparedStatement ps;
      
               String username=jTextField_username.getText();
               String pass1 =jPasswordField_password1.getText();             
                String pass2 =jPasswordField_password2.getText();  
                String course=jTextField_course.getText();
                String fname=jTextField_fname.getText();
                try {
                    user u1 = new user();
                    u1.insertUser(username, u1.getMD5Hash(pass2),course,fname);
                    
                } catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(TeacherSignUp.class.getName()).log(Level.SEVERE, null, ex);
                }
           
            } else{lbl_Pmatch.setVisible(true);}
            jTextField_username.setText("");
            jPasswordField_password1.setText("");
            jPasswordField_password2.setText("");
            jTextField_course.setText("");
            jTextField_fname.setText("");

        }
        
       
    }//GEN-LAST:event_button_addUserActionPerformed

    private void button_addUserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_button_addUserPropertyChange

    }//GEN-LAST:event_button_addUserPropertyChange

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
//        AdminDashboard adduser = new AdminDashboard();
//                       adduser.setVisible(true);
//                       adduser.pack();
//                       adduser.setLocationRelativeTo(null);
//                       adduser.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                       this.dispose();
    }//GEN-LAST:event_button_cancelActionPerformed

    private void button_cancelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_button_cancelPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_button_cancelPropertyChange

    private void jPasswordField_password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_password2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_password2ActionPerformed

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameActionPerformed

    private void jTextField_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_courseActionPerformed

    private void jTextField_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button_addUser;
    private java.awt.Button button_cancel;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_password1;
    private javax.swing.JPasswordField jPasswordField_password2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_course;
    private javax.swing.JTextField jTextField_fname;
    private javax.swing.JTextField jTextField_username;
    private javax.swing.JLabel lbl_P;
    private javax.swing.JLabel lbl_P2;
    private javax.swing.JLabel lbl_Pmatch;
    private javax.swing.JLabel lbl_U;
    // End of variables declaration//GEN-END:variables
}
